### ISSUE TITLE
Multiple underscores cause N807 false-positive

### ISSUE THREAD

**Issue by dmtucker** [PyCQA/pep8-naming#51]
This may be related to #45:
``` python
def foo_():
    pass


def foo__():
    pass


def test___main__():
    """Test python -m functionality."""
    with pytest.raises(SystemExit) as excinfo:
        with unittest.mock.patch('sys.argv', []):
            # pylint: disable=unused-variable, redefined-outer-name
            import backlog.__main__  # noqa: F401
    assert excinfo.value.code == 0
```
```
/home/david/Projects/backlog/tests/test_cli.py:14:5: N802 function name 'foo__' should be lowercase xxx
/home/david/Projects/backlog/tests/test_cli.py:18:5: N802 function name 'test___main__' should be lowercase xxx
```

**Comment by sigmavirus24** [comment]
I'd be happy to merge a PR that fixes this up.

I'm wondering if you could share the reasoning behind using multiple `_`s in your function naming too.

**Comment by dmtucker** [comment]
It's a test of `__main__.py` that is next to tests for `main()`, and that's just what came to mind...
I have a similar test called `test___repr__` which covers multiple objects:
``` python
@pytest.mark.parametrize('obj', [...])
def test___repr__(obj):
    assert obj == eval(repr(obj))
```

**Comment by 5j9** [comment]
Since b656f4a190a30b8c3630f89c2fa71b1c2960ed2a this issue has been assigned a more specific error code (N807: function name should not start or end with '__') so that it can be ignored separately.

Still I'm not sure if this N807 error code is useful enough to be worth to have its false positives: I think it's a valid use case to have dunder function names defined in module scope if the coder wants to convert that module into a `ModuleType` class and then reinsert it into `sys.modules`. Also with [PEP 562](https://www.python.org/dev/peps/pep-0562/) now being part of py3.7, it is now valid for modules to have `__dir__` and `__getattr__` functions defined in them.

Should we remove N807 error code altogether?
Or maybe instead of it, `pep8-naming` should maintain a set of all valid magic object names (`__all__`, `__author__`, `__version__`, `__init__`, `__import__` or `__file__`, etc) in Python and warn if the code tries to define any new magic name that is not in that set... That will be more in line with PEP8 which states: "Never invent such names; only use them as documented."

**Comment by sigmavirus24** [comment]
Well, I think having checks for people to enable is more valuable than not having them at all. If we want to, Flake8's OptionManager on `flake8>=3.0` allows us to extend the default ignore list in https://github.com/PyCQA/pep8-naming/blob/09387c557e2112b89ada55742f2f7134b1a4aa3f/src/pep8ext_naming.py#L102 by doing `parser.extend_default_ignore(['N807'])`

**Comment by sigmavirus24** [comment]
Also, first person to send a PR clarifying that in the Flake8 docs wins internet points that can be redeemed for a drink of your choice at a future PyCon or other conference where we might meet up :)

**Comment by jparise** [comment]
I wonder if we should instead change the N807 logic (and message) from "start *or* end with `__`" to "start *and* end with `__`". That would error on names like `__foo__`, etc. that are generally considered to be special and magic while allowing people to prepend or append `_`'s as much as they like.

With this change, none of the functions in the original code example would be considered an error.
