### ISSUE TITLE
Functions starting/ending with a dunder

### ISSUE THREAD

**Issue by dstufft** [PyCQA/pep8-naming#9]
pep8-naming does not allow functions starting or ending with a dunder (`__`). This is not something that is disallowed by PEP8 and I think this rule should be removed. However if this check remains then it should be moved to it's own check and should not be part of the more general "functions should be lowercase" check so that people can disable it in their own projects without disabling the useful lowercase function check.

**Comment by FichteFoll** [comment]
Dunder functions really shouldn't be marked in this check. 
I do believe a separate check for this is useful because, by themselves, dunder functions have absolutely no different meaning from functions with a single single underscore and thus are redundand.

PEP-8 doesn't have a stance regarding those so the check should probably be disabled by default?
